version: "2"

services:
  motgama_odoo:
    image: motgama
    container_name: motgama_odoo
    build: .
    depends_on:
      - motgama_db
    ports:
      - "8069:8069"
    environment:
      - HOST=motgama_db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - motgama_storage:/var/lib/odoo
      - ./addons_resources:/mnt/addons_resources
      - ./addons_terceros:/mnt/addons_terceros
    
  motgama_db:
    image: postgres:10
    container_name: motgama_db
    ports:
      - "5432:5432"    
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - motgama_pgdata:/var/lib/postgresql/data/pgdata

volumes:
  motgama_storage:
  motgama_pgdata: